### ISSUE TITLE
Hey, cool repo, have you considered making a gh-pages for it?

### ISSUE THREAD

**Issue by hyperswine** [dreamos82/Osdev-Notes#12]
You got a good collection of `.md` files that could be directly implemented into a static site with jekyll. I thought it would be cool for the community to show their notes in a cool way. I have mine here, https://comp6900.github.io/, which is a bit more of a lighthearted 'pseudo course' rn.

**Comment by dreamos82** [comment]
Hey @hyperswine, thanks for your issue. 

Yeah adding github pages is something i was thinking about recently and was talking about it wit @DeanoBurrito , 
I think  i would have them definitely done in the next future. 

I will close this issue when gh-pages will be implemented! 

Thanks again!

**Comment by dreamos82** [comment]
@hyperswine the github pages are deployed, and available at: https://dreamos82.github.io/Osdev-Notes/ 

Thanks for your interest in this project! :)

**Comment by Arnau478** [comment]
It was cool to see the new format! Not a bad `gh-pages` template!

**Comment by dreamos82** [comment]
Thanks! :)
